# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gtfs-realtime-realcity.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'gtfs-realtime-realcity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gtfs_realtime_pb2 as gtfs__realtime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cgtfs-realtime-realcity.proto\x12\x08realcity\x1a\x13gtfs-realtime.proto\"\x83\x01\n\x11VehicleDescriptor\x12\x15\n\rvehicle_model\x18\x01 \x01(\t\x12\x17\n\x08\x64\x65viated\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x14\n\x0cvehicle_type\x18\x03 \x01(\x05\x12\x11\n\tdoor_open\x18\x04 \x01(\x08\x12\x15\n\rstop_distance\x18\x05 \x01(\x05\"\xa0\x01\n\x0eStopTimeUpdate\x12\x45\n\x11scheduled_arrival\x18\x01 \x01(\x0b\x32*.transit_realtime.TripUpdate.StopTimeEvent\x12G\n\x13scheduled_departure\x18\x02 \x01(\x0b\x32*.transit_realtime.TripUpdate.StopTimeEvent\"\x98\x02\n\x0bRouteDetail\x12\x10\n\x08route_id\x18\x01 \x02(\t\x12\x37\n\x0bheader_text\x18\x02 \x01(\x0b\x32\".transit_realtime.TranslatedString\x12,\n\x05\x63\x61use\x18\x03 \x01(\x0e\x32\x1d.transit_realtime.Alert.Cause\x12.\n\x06\x65\x66\x66\x65\x63t\x18\x04 \x01(\x0e\x32\x1e.transit_realtime.Alert.Effect\x12\x35\n\x0b\x65\x66\x66\x65\x63t_type\x18\x05 \x01(\x0e\x32 .realcity.RouteDetail.EffectType\")\n\nEffectType\x12\x0e\n\nNO_SERVICE\x10\x01\x12\x0b\n\x07WARNING\x10\x02\"\xaf\x01\n\x05\x41lert\x12\x35\n\tstartText\x18\x01 \x01(\x0b\x32\".transit_realtime.TranslatedString\x12\x33\n\x07\x65ndText\x18\x02 \x01(\x0b\x32\".transit_realtime.TranslatedString\x12\x14\n\x0cmodifiedTime\x18\x03 \x01(\x04\x12$\n\x05route\x18\x04 \x03(\x0b\x32\x15.realcity.RouteDetail:R\n\x07vehicle\x12#.transit_realtime.VehicleDescriptor\x18\xee\x07 \x01(\x0b\x32\x1b.realcity.VehicleDescriptor:`\n\x10stop_time_update\x12+.transit_realtime.TripUpdate.StopTimeUpdate\x18\xee\x07 \x01(\x0b\x32\x18.realcity.StopTimeUpdate:8\n\x05\x61lert\x12\x17.transit_realtime.Alert\x18\xee\x07 \x01(\x0b\x32\x0f.realcity.Alert')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gtfs_realtime_realcity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VEHICLEDESCRIPTOR']._serialized_start=64
  _globals['_VEHICLEDESCRIPTOR']._serialized_end=195
  _globals['_STOPTIMEUPDATE']._serialized_start=198
  _globals['_STOPTIMEUPDATE']._serialized_end=358
  _globals['_ROUTEDETAIL']._serialized_start=361
  _globals['_ROUTEDETAIL']._serialized_end=641
  _globals['_ROUTEDETAIL_EFFECTTYPE']._serialized_start=600
  _globals['_ROUTEDETAIL_EFFECTTYPE']._serialized_end=641
  _globals['_ALERT']._serialized_start=644
  _globals['_ALERT']._serialized_end=819
# @@protoc_insertion_point(module_scope)
